@php($package=$package??null)
@if($errors->any())<div class="alert alert-danger"><strong>Please correct the highlighted fields.</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="package-tabs-nav mb-4">
<ul class="nav nav-tabs flex-nowrap" role="tablist">@foreach(['basic'=>'1. Basic Information','relations'=>'2. Destinations & Styles','images'=>'3. Images','itinerary'=>'4. Itinerary','highlights'=>'5. Highlights','items'=>'6. Inclusions & Exclusions','policies'=>'7. Accommodation & Policies','faqs'=>'8. FAQs','reviews'=>'9. Reviews','seo'=>'10. SEO'] as $id=>$label)<li class="nav-item" role="presentation"><button class="nav-link text-nowrap {{ $loop->first?'active':'' }}" id="tab-{{ $id }}-button" data-bs-toggle="tab" data-bs-target="#tab-{{ $id }}" type="button" role="tab" aria-controls="tab-{{ $id }}" aria-selected="{{ $loop->first ? 'true' : 'false' }}">{{ $label }}</button></li>@endforeach</ul>
</div>
<div class="card admin-card package-form-card"><div class="card-body p-4"><div class="tab-content package-form-tabs">
<div class="tab-pane fade show active" id="tab-basic" data-package-section="basic">@include('admin.packages.partials.basic')</div>
<div class="tab-pane fade" id="tab-relations" data-package-section="relations"><div class="row"><div class="col-md-6"><label class="form-label">Destinations</label><select class="form-select" name="destination_ids[]" multiple size="12">@php($selectedDestinations=old('destination_ids',$package?->destinations->pluck('id')->all()??[]))@foreach($destinations as $destination)<option value="{{ $destination->id }}" @selected(in_array($destination->id,$selectedDestinations))>{{ $destination->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Travel styles</label><select class="form-select" name="travel_style_ids[]" multiple size="12">@php($selectedStyles=old('travel_style_ids',$package?->travelStyles->pluck('id')->all()??[]))@foreach($travelStyles as $style)<option value="{{ $style->id }}" @selected(in_array($style->id,$selectedStyles))>{{ $style->name }}</option>@endforeach</select></div></div></div>
<div class="tab-pane fade" id="tab-images" data-package-section="images">@include('admin.packages.partials.images')</div>
<div class="tab-pane fade" id="tab-itinerary" data-package-section="itinerary">@include('admin.packages.partials.itineraries')</div>
<div class="tab-pane fade" id="tab-highlights" data-package-section="highlights">@include('admin.packages.partials.highlights')</div>
<div class="tab-pane fade" id="tab-items" data-package-section="items">@include('admin.packages.partials.items')</div>
<div class="tab-pane fade" id="tab-policies" data-package-section="policies">@include('admin.packages.partials.policies')</div>
<div class="tab-pane fade" id="tab-faqs" data-package-section="faqs">@include('admin.packages.partials.faqs')</div>
<div class="tab-pane fade" id="tab-reviews" data-package-section="reviews">@include('admin.packages.partials.reviews')</div>
<div class="tab-pane fade" id="tab-seo" data-package-section="seo"><x-admin.form-input name="meta_title" label="Meta title" :value="$package?->meta_title" /><x-admin.form-textarea name="meta_description" label="Meta description" :value="$package?->meta_description" rows="4" /></div>
</div></div></div>
@push('scripts')<script>document.querySelectorAll('[data-repeater-add]').forEach(button=>button.addEventListener('click',()=>{const target=document.getElementById(button.dataset.repeaterAdd),template=document.getElementById(button.dataset.template),index=Number(target.dataset.nextIndex||target.children.length);target.insertAdjacentHTML('beforeend',template.innerHTML.replaceAll('__INDEX__',index));target.dataset.nextIndex=index+1;}));document.addEventListener('click',event=>{const button=event.target.closest('[data-remove-new-row]');if(button)button.closest('[data-repeater-row]').remove();});document.querySelectorAll('[data-preview]').forEach(input=>input.addEventListener('change',()=>{const file=input.files[0],target=document.getElementById(input.dataset.preview);if(file&&target&&file.type.startsWith('image/'))target.innerHTML=`<img src="${URL.createObjectURL(file)}" alt="Upload preview">`;}));
const packageForm=document.querySelector('form[data-package-section-url]');if(packageForm){document.querySelectorAll('[data-package-section]').forEach(pane=>{const actions=document.createElement('div');actions.className='border-top mt-4 pt-3 d-flex align-items-center gap-3';actions.innerHTML=`<button type="button" class="btn btn-admin-primary" data-save-package-section>Save this section</button><span class="small" aria-live="polite" data-section-feedback></span>`;pane.appendChild(actions);});const savedSection=sessionStorage.getItem('package-edit-section');if(savedSection){sessionStorage.removeItem('package-edit-section');const tabButton=document.getElementById(`tab-${savedSection}-button`);if(tabButton&&window.bootstrap)new bootstrap.Tab(tabButton).show();}packageForm.addEventListener('click',async event=>{const button=event.target.closest('[data-save-package-section]');if(!button)return;const pane=button.closest('[data-package-section]'),feedback=pane.querySelector('[data-section-feedback]'),data=new FormData();data.append('_token',packageForm.querySelector('[name="_token"]').value);data.append('section',pane.dataset.packageSection);pane.querySelectorAll('input,select,textarea').forEach(control=>{if(!control.name||control.disabled)return;if((control.type==='checkbox'||control.type==='radio')&&!control.checked)return;if(control.type==='file'){Array.from(control.files).forEach(file=>data.append(control.name,file));return;}if(control.tagName==='SELECT'&&control.multiple){Array.from(control.selectedOptions).forEach(option=>data.append(control.name,option.value));return;}data.append(control.name,control.value);});button.disabled=true;feedback.className='small text-muted';feedback.textContent='Saving…';try{const response=await fetch(packageForm.dataset.packageSectionUrl,{method:'POST',body:data,headers:{Accept:'application/json'}});const result=await response.json().catch(()=>({}));if(!response.ok){const errors=result.errors?Object.values(result.errors).flat().join(' '):(result.message||'Unable to save this section.');throw new Error(errors);}feedback.className='small text-success';feedback.textContent=result.message||'Section saved.';sessionStorage.setItem('package-edit-section',pane.dataset.packageSection);window.setTimeout(()=>window.location.reload(),500);}catch(error){feedback.className='small text-danger';feedback.textContent=error.message;}finally{button.disabled=false;}});}</script>@endpush
