@php($package=$package??null)
@if($errors->any())<div class="alert alert-danger"><strong>Please correct the highlighted fields.</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="package-tabs-nav mb-4">
<ul class="nav nav-tabs flex-nowrap" role="tablist">@foreach(['basic'=>'1. Basic Information','relations'=>'2. Destinations & Styles','images'=>'3. Images','itinerary'=>'4. Itinerary','highlights'=>'5. Highlights','items'=>'6. Inclusions & Exclusions','policies'=>'7. Accommodation & Policies','faqs'=>'8. FAQs','reviews'=>'9. Reviews','seo'=>'10. SEO'] as $id=>$label)<li class="nav-item" role="presentation"><button class="nav-link text-nowrap {{ $loop->first?'active':'' }}" id="tab-{{ $id }}-button" data-bs-toggle="tab" data-bs-target="#tab-{{ $id }}" type="button" role="tab" aria-controls="tab-{{ $id }}" aria-selected="{{ $loop->first ? 'true' : 'false' }}">{{ $label }}</button></li>@endforeach</ul>
</div>
<div class="card admin-card package-form-card"><div class="card-body p-4"><div class="tab-content package-form-tabs">
<div class="tab-pane fade show active" id="tab-basic">@include('admin.packages.partials.basic')</div>
<div class="tab-pane fade" id="tab-relations"><div class="row"><div class="col-md-6"><label class="form-label">Destinations</label><select class="form-select" name="destination_ids[]" multiple size="12">@php($selectedDestinations=old('destination_ids',$package?->destinations->pluck('id')->all()??[]))@foreach($destinations as $destination)<option value="{{ $destination->id }}" @selected(in_array($destination->id,$selectedDestinations))>{{ $destination->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Travel styles</label><select class="form-select" name="travel_style_ids[]" multiple size="12">@php($selectedStyles=old('travel_style_ids',$package?->travelStyles->pluck('id')->all()??[]))@foreach($travelStyles as $style)<option value="{{ $style->id }}" @selected(in_array($style->id,$selectedStyles))>{{ $style->name }}</option>@endforeach</select></div></div></div>
<div class="tab-pane fade" id="tab-images">@include('admin.packages.partials.images')</div>
<div class="tab-pane fade" id="tab-itinerary">@include('admin.packages.partials.itineraries')</div>
<div class="tab-pane fade" id="tab-highlights">@include('admin.packages.partials.highlights')</div>
<div class="tab-pane fade" id="tab-items">@include('admin.packages.partials.items')</div>
<div class="tab-pane fade" id="tab-policies">@include('admin.packages.partials.policies')</div>
<div class="tab-pane fade" id="tab-faqs">@include('admin.packages.partials.faqs')</div>
<div class="tab-pane fade" id="tab-reviews">@include('admin.packages.partials.reviews')</div>
<div class="tab-pane fade" id="tab-seo"><x-admin.form-input name="meta_title" label="Meta title" :value="$package?->meta_title" /><x-admin.form-textarea name="meta_description" label="Meta description" :value="$package?->meta_description" rows="4" /></div>
</div></div></div>
@push('scripts')<script>document.querySelectorAll('[data-repeater-add]').forEach(button=>button.addEventListener('click',()=>{const target=document.getElementById(button.dataset.repeaterAdd),template=document.getElementById(button.dataset.template),index=Number(target.dataset.nextIndex||target.children.length);target.insertAdjacentHTML('beforeend',template.innerHTML.replaceAll('__INDEX__',index));target.dataset.nextIndex=index+1;}));document.addEventListener('click',event=>{const button=event.target.closest('[data-remove-new-row]');if(button)button.closest('[data-repeater-row]').remove();});document.querySelectorAll('[data-preview]').forEach(input=>input.addEventListener('change',()=>{const file=input.files[0],target=document.getElementById(input.dataset.preview);if(file&&target&&file.type.startsWith('image/'))target.innerHTML=`<img src="${URL.createObjectURL(file)}" alt="Upload preview">`;}));</script>@endpush
