@php($destination = $destination ?? null)
@if($errors->any())<div class="alert alert-danger"><strong>Please correct the highlighted fields.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

<div class="card admin-card mb-4"><div class="card-header bg-white py-3"><h2 class="h5 mb-0">1. Basic Information</h2></div><div class="card-body row">
    <div class="col-md-6"><x-admin.form-select name="destination_region_id" label="Region" :options="$regions->pluck('name','id')->all()" :selected="$destination?->destination_region_id" required /></div><div class="col-md-6"><x-admin.form-input name="name" label="Name" :value="$destination?->name" required /></div>
    <div class="col-12"><x-admin.form-input name="slug" label="Slug" :value="$destination?->slug" help="Leave blank to generate it from the name. Duplicate slugs receive a numeric suffix." /></div>
    <div class="col-12"><x-admin.form-textarea name="short_description" label="Short description" :value="$destination?->short_description" rows="3" /></div><div class="col-12"><x-admin.form-textarea name="full_description" label="Full description" :value="$destination?->full_description" rows="8" /></div>
</div></div>

<div class="card admin-card mb-4"><div class="card-header bg-white py-3"><h2 class="h5 mb-0">2. Cover Image</h2></div><div class="card-body row g-3"><div class="col-md-7"><label class="form-label" for="cover_image">Cover image</label><input class="form-control @error('cover_image') is-invalid @enderror" type="file" id="cover_image" name="cover_image" accept="image/jpeg,image/png,image/webp" data-image-preview="cover-preview">@error('cover_image')<div class="invalid-feedback">{{ $message }}</div>@enderror @if($destination?->cover_image)<div class="form-check mt-3"><input type="hidden" name="remove_cover_image" value="0"><input class="form-check-input" type="checkbox" value="1" id="remove_cover_image" name="remove_cover_image"><label class="form-check-label text-danger" for="remove_cover_image">Remove current cover image</label></div>@endif</div><div class="col-md-5"><x-admin.image-preview id="cover-preview" :src="$destination?->cover_image ? Storage::disk('public')->url($destination->cover_image) : null" alt="Cover image preview" /></div></div></div>

@include('admin.destinations.partials.gallery')
@include('admin.destinations.partials.attractions')
@include('admin.destinations.partials.activities')
@include('admin.destinations.partials.travel-tips')

<div class="card admin-card mb-4"><div class="card-header bg-white py-3"><h2 class="h5 mb-0">7. Map and Best Time</h2></div><div class="card-body row"><div class="col-12"><x-admin.form-input name="best_time_to_visit" label="Best time to visit" :value="$destination?->best_time_to_visit" /></div><div class="col-md-6"><x-admin.form-input name="latitude" label="Latitude" type="number" step="0.0000001" min="-90" max="90" :value="$destination?->latitude" /></div><div class="col-md-6"><x-admin.form-input name="longitude" label="Longitude" type="number" step="0.0000001" min="-180" max="180" :value="$destination?->longitude" /></div></div></div>
<div class="card admin-card mb-4"><div class="card-header bg-white py-3"><h2 class="h5 mb-0">8. SEO</h2></div><div class="card-body"><x-admin.form-input name="meta_title" label="Meta title" :value="$destination?->meta_title" /><x-admin.form-textarea name="meta_description" label="Meta description" :value="$destination?->meta_description" rows="3" /></div></div>
<div class="card admin-card"><div class="card-header bg-white py-3"><h2 class="h5 mb-0">9. Publishing Settings</h2></div><div class="card-body row"><div class="col-md-4"><x-admin.form-input name="display_order" label="Display order" type="number" min="0" :value="$destination?->display_order ?? 0" required /></div><div class="col-md-8 d-flex gap-4 align-items-center"><div class="form-check form-switch"><input type="hidden" name="is_featured" value="0"><input class="form-check-input" type="checkbox" id="is_featured" name="is_featured" value="1" @checked(old('is_featured',$destination?->is_featured ?? false))><label class="form-check-label" for="is_featured">Featured</label></div><div class="form-check form-switch"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" id="is_active" name="is_active" value="1" @checked(old('is_active',$destination?->is_active ?? true))><label class="form-check-label" for="is_active">Active</label></div></div></div></div>

@push('scripts')<script>
document.querySelectorAll('[data-image-preview]').forEach(input => input.addEventListener('change', () => { const file=input.files[0], target=document.getElementById(input.dataset.imagePreview); if(file&&target){ target.innerHTML=''; const image=document.createElement('img'); image.src=URL.createObjectURL(file); image.alt='Selected image preview'; target.appendChild(image); }}));
document.querySelectorAll('[data-repeater-add]').forEach(button => button.addEventListener('click', () => { const target=document.getElementById(button.dataset.repeaterAdd), template=document.getElementById(button.dataset.template); const index=Number(target.dataset.nextIndex || target.children.length); target.insertAdjacentHTML('beforeend', template.innerHTML.replaceAll('__INDEX__', index)); target.dataset.nextIndex=index+1; }));
document.addEventListener('click', event => { const button=event.target.closest('[data-remove-new-row]'); if(button) button.closest('[data-repeater-row]').remove(); });
</script>@endpush
