@extends('layouts.admin', ['title' => 'Experiences', 'description' => 'Manage experiences, pricing, media, and publishing.'])
@section('page-actions')
    @can('experiences.create')
        <a href="{{ route('admin.experiences.create') }}" class="btn btn-admin-primary">Add experience</a>
    @endcan
@endsection
@section('content')
<div class="card admin-card mb-4"><div class="card-body"><form method="GET" class="row g-3 align-items-end"><div class="col-lg-3"><label class="form-label">Search</label><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Title or slug"></div><div class="col-sm-6 col-lg-2"><label class="form-label">Category</label><select class="form-select" name="category"><option value="">All</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)request('category')===(string)$category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="col-sm-6 col-lg-2"><label class="form-label">Destination</label><select class="form-select" name="destination"><option value="">All</option>@foreach($destinations as $destination)<option value="{{ $destination->id }}" @selected((string)request('destination')===(string)$destination->id)>{{ $destination->name }}</option>@endforeach</select></div><div class="col-sm-4 col-lg-1"><label class="form-label">Featured</label><select class="form-select" name="featured"><option value="">All</option><option value="yes" @selected(request('featured')==='yes')>Yes</option><option value="no" @selected(request('featured')==='no')>No</option></select></div><div class="col-sm-4 col-lg-2"><label class="form-label">Status</label><select class="form-select" name="status"><option value="">All</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option><option value="trashed" @selected(request('status')==='trashed')>Trashed</option></select></div><div class="col-sm-4 col-lg-2 d-flex gap-2"><button class="btn btn-admin-primary flex-grow-1">Filter</button><a href="{{ route('admin.experiences.index') }}" class="btn btn-outline-secondary">Reset</a></div></form></div></div>
<div class="card admin-card"><div class="card-body p-0"><div class="table-responsive"><table class="table admin-table align-middle mb-0"><thead><tr><th class="ps-4">Experience</th><th>Category</th><th>Destination</th><th>Price</th><th>Status</th><th class="text-end pe-4">Actions</th></tr></thead><tbody>@forelse($experiences as $experience)<tr><td class="ps-4"><div class="d-flex gap-3 align-items-center">@if($experience->cover_image)<img src="{{ Storage::disk('public')->url($experience->cover_image) }}" alt="" class="rounded object-fit-cover" width="64" height="48">@endif<div><strong>{{ $experience->title }}</strong><div class="small text-muted">{{ $experience->slug }}</div>@if($experience->is_featured)<span class="badge text-bg-success">Featured</span>@endif @if($experience->is_popular)<span class="badge text-bg-warning">Popular</span>@endif</div></div></td><td>{{ $experience->category?->name ?: 'Uncategorized' }}</td><td>{{ $experience->destination?->name ?: 'Unavailable destination' }}</td><td>{{ $experience->starting_price !== null ? $experience->currency.' '.$experience->starting_price : '—' }}</td><td><span class="badge {{ $experience->is_active ? 'text-bg-success':'text-bg-secondary' }}">{{ $experience->is_active ? 'Active':'Inactive' }}</span></td><td class="text-end pe-4 text-nowrap">@if($experience->trashed())@can('experiences.delete')<form class="d-inline" method="POST" action="{{ route('admin.experiences.restore',$experience->id) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-success">Restore</button></form>@endcan @else @can('experiences.update')<form class="d-inline" method="POST" action="{{ route('admin.experiences.toggle',$experience->id) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-secondary">{{ $experience->is_active?'Deactivate':'Activate' }}</button></form><a href="{{ route('admin.experiences.edit',$experience->id) }}" class="btn btn-sm btn-outline-primary">Edit</a>@endcan @can('experiences.delete')<button class="btn btn-sm btn-outline-danger" data-bs-toggle="modal" data-bs-target="#confirmationModal" data-confirm-action="{{ route('admin.experiences.destroy',$experience->id) }}" data-confirm-message="Move {{ $experience->title }} to trash?">Delete</button>@endcan @endif</td></tr>@empty<tr><td colspan="6"><div class="admin-empty m-3">No experiences found.</div></td></tr>@endforelse</tbody></table></div></div>@if($experiences->hasPages())<div class="card-footer bg-white border-0">{{ $experiences->links('pagination::bootstrap-5') }}</div>@endif</div>
@endsection
