@extends('layouts.admin', ['title' => 'Users', 'description' => 'Manage administrative users and their access roles.'])

@section('page-actions')
    <a class="btn btn-admin-primary" href="{{ route('admin.users.create') }}">Add administrator</a>
@endsection

@section('content')
    <div class="card admin-card mb-4"><div class="card-body"><form class="row g-3 align-items-end" method="GET"><div class="col-md-7"><label class="form-label" for="search">Search</label><input class="form-control" id="search" name="search" value="{{ request('search') }}" placeholder="Name or email"></div><div class="col-md-3"><label class="form-label" for="role">Role</label><select class="form-select" id="role" name="role"><option value="">All roles</option>@foreach($roles as $role)<option value="{{ $role->name }}" @selected(request('role') === $role->name)>{{ str($role->name)->replace('_', ' ')->title() }}</option>@endforeach</select></div><div class="col-md-2 d-flex gap-2"><button class="btn btn-admin-primary">Filter</button><a class="btn btn-outline-secondary" href="{{ route('admin.users.index') }}">Reset</a></div></form></div></div>
    <div class="card admin-card"><div class="table-responsive"><table class="table admin-table align-middle mb-0"><thead><tr><th class="ps-4">Administrator</th><th>Roles</th><th>Verified</th><th>Last updated</th><th class="text-end pe-4">Actions</th></tr></thead><tbody>@forelse($users as $user)<tr><td class="ps-4"><div class="d-flex align-items-center gap-3"><span class="admin-user-avatar">{{ strtoupper(substr($user->name, 0, 1)) }}</span><div><strong>{{ $user->name }}</strong><small class="d-block text-muted">{{ $user->email }}</small></div></div></td><td>@forelse($user->roles as $role)<span class="badge text-bg-success me-1">{{ str($role->name)->replace('_', ' ')->title() }}</span>@empty<span class="text-muted">No role</span>@endforelse</td><td><span class="badge {{ $user->email_verified_at ? 'text-bg-success' : 'text-bg-warning' }}">{{ $user->email_verified_at ? 'Verified' : 'Pending' }}</span></td><td>{{ $user->updated_at?->format('d M Y') }}</td><td class="text-end pe-4 text-nowrap"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.users.edit', $user) }}">Edit</a>@if(! auth()->user()->is($user))<button class="btn btn-sm btn-outline-danger" type="button" data-bs-toggle="modal" data-bs-target="#confirmationModal" data-confirm-action="{{ route('admin.users.destroy', $user) }}" data-confirm-message="Delete administrator {{ $user->name }}?">Delete</button>@endif</td></tr>@empty<tr><td colspan="5"><div class="admin-empty m-3">No administrators found.</div></td></tr>@endforelse</tbody></table></div>@if($users->hasPages())<div class="card-footer bg-white border-0">{{ $users->links('pagination::bootstrap-5') }}</div>@endif</div>
@endsection
