@php($experience=$experience??null)
@if($errors->any())<div class="alert alert-danger"><strong>Please correct the highlighted fields.</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card admin-card mb-4"><div class="card-header bg-white py-3"><h2 class="h5 mb-0">1. Basic Information</h2></div><div class="card-body row"><div class="col-md-6"><x-admin.form-select name="experience_category_id" label="Experience category" :options="$categories->pluck('name','id')->all()" :selected="$experience?->experience_category_id" required /></div><div class="col-md-6"><x-admin.form-input name="title" label="Title" :value="$experience?->title" required /></div><div class="col-md-8"><x-admin.form-input name="slug" label="Slug" :value="$experience?->slug" help="Leave blank to generate automatically." /></div><div class="col-md-4"><x-admin.form-input name="badge_text" label="Badge text" :value="$experience?->badge_text" /></div><div class="col-12"><x-admin.form-textarea name="short_description" label="Short description" :value="$experience?->short_description" rows="3" /></div><div class="col-12"><x-admin.form-textarea name="full_description" label="Full description" :value="$experience?->full_description" rows="8" /></div></div></div>
<div class="card admin-card mb-4"><div class="card-header bg-white py-3"><h2 class="h5 mb-0">2. Destination and Travel Styles</h2></div><div class="card-body row"><div class="col-md-6"><x-admin.form-select name="destination_id" label="Destination" :options="$destinations->pluck('name','id')->all()" :selected="$experience?->destination_id" required /></div><div class="col-md-6"><label class="form-label" for="travel_style_ids">Travel styles</label><select class="form-select" id="travel_style_ids" name="travel_style_ids[]" multiple size="6">@php($selectedStyles=old('travel_style_ids',$experience?->travelStyles->pluck('id')->all()??[]))@foreach($travelStyles as $style)<option value="{{ $style->id }}" @selected(in_array($style->id,$selectedStyles))>{{ $style->name }}</option>@endforeach</select><div class="form-text">Hold Ctrl or Command to select multiple.</div></div></div></div>
@include('admin.experiences.partials.images')
@include('admin.experiences.partials.item-repeater',['number'=>4,'title'=>'Highlights','input'=>'highlights','items'=>$experience?->highlights??collect()])
@include('admin.experiences.partials.item-repeater',['number'=>5,'title'=>'Inclusions','input'=>'inclusions','items'=>$experience?->inclusions??collect()])
@include('admin.experiences.partials.item-repeater',['number'=>6,'title'=>'Exclusions','input'=>'exclusions','items'=>$experience?->exclusions??collect()])
<div class="card admin-card mb-4"><div class="card-header bg-white py-3"><h2 class="h5 mb-0">7. Location and Pricing</h2></div><div class="card-body row"><div class="col-md-6"><x-admin.form-input name="location" label="Location" :value="$experience?->location" /></div><div class="col-md-3"><x-admin.form-input name="duration_value" label="Duration value" type="number" min="1" :value="$experience?->duration_value" /></div><div class="col-md-3"><x-admin.form-input name="duration_unit" label="Duration unit" :value="$experience?->duration_unit" placeholder="Hours or days" /></div><div class="col-md-4"><x-admin.form-input name="starting_price" label="Starting price" type="number" min="0" step="0.01" :value="$experience?->starting_price" /></div><div class="col-md-2"><x-admin.form-input name="currency" label="Currency" :value="$experience?->currency??'USD'" maxlength="3" required /></div><div class="col-md-3"><x-admin.form-input name="latitude" label="Latitude" type="number" min="-90" max="90" step="0.0000001" :value="$experience?->latitude" /></div><div class="col-md-3"><x-admin.form-input name="longitude" label="Longitude" type="number" min="-180" max="180" step="0.0000001" :value="$experience?->longitude" /></div><div class="col-12"><x-admin.form-textarea name="important_information" label="Important information" :value="$experience?->important_information" rows="4" /></div></div></div>
<div class="card admin-card mb-4"><div class="card-header bg-white py-3"><h2 class="h5 mb-0">8. SEO</h2></div><div class="card-body"><x-admin.form-input name="meta_title" label="Meta title" :value="$experience?->meta_title" /><x-admin.form-textarea name="meta_description" label="Meta description" :value="$experience?->meta_description" rows="3" /></div></div>
<div class="card admin-card"><div class="card-header bg-white py-3"><h2 class="h5 mb-0">9. Publishing</h2></div><div class="card-body row"><div class="col-md-4"><x-admin.form-input name="display_order" label="Display order" type="number" min="0" :value="$experience?->display_order??0" required /></div><div class="col-md-8 d-flex flex-wrap gap-4 align-items-center">@foreach(['is_featured'=>'Featured','is_popular'=>'Popular','is_active'=>'Active'] as $field=>$label)<div class="form-check form-switch"><input type="hidden" name="{{ $field }}" value="0"><input class="form-check-input" type="checkbox" id="{{ $field }}" name="{{ $field }}" value="1" @checked(old($field,$experience?->{$field}??($field==='is_active')))><label class="form-check-label" for="{{ $field }}">{{ $label }}</label></div>@endforeach</div></div></div>
@push('scripts')<script>document.querySelectorAll('[data-repeater-add]').forEach(button=>button.addEventListener('click',()=>{const target=document.getElementById(button.dataset.repeaterAdd),template=document.getElementById(button.dataset.template),index=Number(target.dataset.nextIndex||target.children.length);target.insertAdjacentHTML('beforeend',template.innerHTML.replaceAll('__INDEX__',index));target.dataset.nextIndex=index+1;}));document.addEventListener('click',event=>{const button=event.target.closest('[data-remove-new-row]');if(button)button.closest('[data-repeater-row]').remove();});document.getElementById('cover_image')?.addEventListener('change',event=>{const file=event.target.files[0],target=document.getElementById('experience-cover-preview');if(file&&target){target.innerHTML=`<img src="${URL.createObjectURL(file)}" alt="Selected cover preview">`;}});</script>@endpush
